#!/bin/bash

echo "🔍 Verifying Serious Business Project Structure..."
echo ""

# Check directories
echo "✓ Checking directories..."
[ -d "pages" ] && echo "  ✅ pages/" || echo "  ❌ pages/"
[ -d "components" ] && echo "  ✅ components/" || echo "  ❌ components/"
[ -d "styles" ] && echo "  ✅ styles/" || echo "  ❌ styles/"
[ -d "public" ] && echo "  ✅ public/" || echo "  ❌ public/"

echo ""
echo "✓ Checking key files..."
[ -f "package.json" ] && echo "  ✅ package.json" || echo "  ❌ package.json"
[ -f "tailwind.config.js" ] && echo "  ✅ tailwind.config.js" || echo "  ❌ tailwind.config.js"
[ -f "tsconfig.json" ] && echo "  ✅ tsconfig.json" || echo "  ❌ tsconfig.json"
[ -f "next.config.js" ] && echo "  ✅ next.config.js" || echo "  ❌ next.config.js"
[ -f ".env.local.example" ] && echo "  ✅ .env.local.example" || echo "  ❌ .env.local.example"

echo ""
echo "✓ Checking pages..."
[ -f "pages/_app.tsx" ] && echo "  ✅ pages/_app.tsx" || echo "  ❌ pages/_app.tsx"
[ -f "pages/_document.tsx" ] && echo "  ✅ pages/_document.tsx" || echo "  ❌ pages/_document.tsx"
[ -f "pages/index.tsx" ] && echo "  ✅ pages/index.tsx" || echo "  ❌ pages/index.tsx"
[ -f "pages/contact.tsx" ] && echo "  ✅ pages/contact.tsx" || echo "  ❌ pages/contact.tsx"
[ -f "pages/api/chat.ts" ] && echo "  ✅ pages/api/chat.ts" || echo "  ❌ pages/api/chat.ts"
[ -f "pages/api/notify.ts" ] && echo "  ✅ pages/api/notify.ts" || echo "  ❌ pages/api/notify.ts"

echo ""
echo "✓ Checking components..."
[ -f "components/Hero.tsx" ] && echo "  ✅ components/Hero.tsx" || echo "  ❌ components/Hero.tsx"
[ -f "components/About.tsx" ] && echo "  ✅ components/About.tsx" || echo "  ❌ components/About.tsx"
[ -f "components/Services.tsx" ] && echo "  ✅ components/Services.tsx" || echo "  ❌ components/Services.tsx"
[ -f "components/ChatWindow.tsx" ] && echo "  ✅ components/ChatWindow.tsx" || echo "  ❌ components/ChatWindow.tsx"
[ -f "components/Footer.tsx" ] && echo "  ✅ components/Footer.tsx" || echo "  ❌ components/Footer.tsx"
[ -f "components/Logo.tsx" ] && echo "  ✅ components/Logo.tsx" || echo "  ❌ components/Logo.tsx"

echo ""
echo "✓ Checking assets..."
[ -f "public/SB_logo_full_lockup.jpg" ] && echo "  ✅ public/SB_logo_full_lockup.jpg" || echo "  ❌ public/SB_logo_full_lockup.jpg"
[ -f "public/SB_icon.jpg" ] && echo "  ✅ public/SB_icon.jpg" || echo "  ❌ public/SB_icon.jpg"
[ -f "public/SB_favicon.jpg" ] && echo "  ✅ public/SB_favicon.jpg" || echo "  ❌ public/SB_favicon.jpg"
[ -f "public/SB_wordmark.jpg" ] && echo "  ✅ public/SB_wordmark.jpg" || echo "  ❌ public/SB_wordmark.jpg"

echo ""
echo "✓ Checking documentation..."
[ -f "README.md" ] && echo "  ✅ README.md" || echo "  ❌ README.md"
[ -f "DEPLOYMENT.md" ] && echo "  ✅ DEPLOYMENT.md" || echo "  ❌ DEPLOYMENT.md"
[ -f "TESTING.md" ] && echo "  ✅ TESTING.md" || echo "  ❌ TESTING.md"
[ -f "CUSTOMIZATION.md" ] && echo "  ✅ CUSTOMIZATION.md" || echo "  ❌ CUSTOMIZATION.md"
[ -f "SHIP.md" ] && echo "  ✅ SHIP.md" || echo "  ❌ SHIP.md"

echo ""
echo "✅ Project structure verified!"
echo ""
echo "Next steps:"
echo "  1. npm install"
echo "  2. Copy .env.local.example to .env.local"
echo "  3. Add your API keys"
echo "  4. npm run dev"
echo ""
echo "For deployment: see DEPLOYMENT.md"
